spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME:unisys}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASS:password}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 1800000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: false
  
  # Add retry configuration for database connection
  sql:
    init:
      continue-on-error: true
      mode: always
